name: Build Lab Tutorial PDF

on:
  push:
    paths:
      - "lab-tutorial/**"
      - ".github/workflows/build-labs.yml"
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lab-tutorial.tex

      - name: Make the name of the PDF file with the commit hash
        run: |
          mv lab-tutorial.pdf lab-tutorial-$(git describe --long --tags --all | sed 's/heads\///g').pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: lab-tutorial-${{ github.sha }}
          path: lab-tutorial-*.pdf
